[project]
name = "speckle-ifcx"
version = "0.1.0"
description = "Interop between Speckle and IFC"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "geopandas>=1.0.1",
    "jupyter>=1.1.1",
    "specklepy>=2.21.2",
]
